### ISSUE TITLE
option to save a drawing as json and reload it for editing

### ISSUE THREAD

**Issue by trentonmercer** [wobsoriano/rn-perfect-sketch-canvas#1]
Would love to see this functionality added, great work on this component!

**Comment by wobsoriano** [comment]
I added `toPoints` and `addPoints` methods in v0.1.2. It returns the point groups from the canvas:

```ts
conts data = canvasRef.current?.toPoints() // [x, y][][]

canvasRef.current?.addPoints(data) // reload for editing
```

**Comment by robertherber** [comment]
@wobsoriano That's great! Would it be possible to add the color (and stroke width) of the point as well?

**Comment by TwanLuttik** [comment]
@robertherber i have made an issue and open pr if you would like to follow 

- https://github.com/wobsoriano/rn-perfect-sketch-canvas/issues/8

**Comment by wobsoriano** [comment]
thank you @TwanLuttik
