### ISSUE TITLE
cannot read undefined property (useCanvasRef)

### ISSUE THREAD

**Issue by soorajpandey** [wobsoriano/rn-perfect-sketch-canvas#10]
hello @wobsoriano, I am getting an issue after updating the library to the latest version 0.1.6, it was not there in the previous version, I know it is from @shopify/react-native-skia side, but I didn't change anything in the skia library.

thank you.
<img width="1080" alt="IMG_780FDE91C366-1" src="https://user-images.githubusercontent.com/42384377/179450925-777af0e6-ce86-45a1-863c-636741824ec4.png">

**Comment by wobsoriano** [comment]
Thanks for reporting! Will take a look later

**Comment by soorajpandey** [comment]
it is fixed now, I created a new folder and installed everything again, copied all the previous files, and it worked. still not sure what was the issue after the update.

**Comment by soorajpandey** [comment]
hello, I have a question, when I am trying to map by the canvas not working (responding),
```
{dataPoints && dataPoints.map((item, key) => {
     console.log(item.id === showImage.id);
      if (item.id === showImage.id) {
         <SketchCanvas
               strokeColor={snap.strokeColor}
               strokeWidth={snap.strokeWidth}
                ref={canvasRef.current?.addPoints(item.points)}
                containerStyle={styles.container}
           />
       }
})}
```
item.points has array of points
thank you
