### ISSUE TITLE
toBase64 crashes app

### ISSUE THREAD

**Issue by abdullahIsa** [wobsoriano/rn-perfect-sketch-canvas#14]
Hello, whenever i tried using canvasRef.current.toBase64(); the app crashes without any error, other types of converter seems ok, how can i resolve this ? thanks.

**Comment by doublelam** [comment]
Hi, I found this issue as well, you can use canvasRef.current.toImage(). encodeToBase64() instead of it. using incorrect ImageFormat type caused it I guess.

**Comment by doublelam** [comment]
> Hello, whenever i tried using canvasRef.current.toBase64(); the app crashes without any error, other types of converter seems ok, how can i resolve this ? thanks.

Hi, I found this issue as well, you can use canvasRef.current.toImage().encodeToBase64() instead of it. it's being used incorrect ImageFormat type caused it I guess.

**Comment by abdullahIsa** [comment]
> > Hello, whenever i tried using canvasRef.current.toBase64(); the app crashes without any error, other types of converter seems ok, how can i resolve this ? thanks.
> 
> Hi, I found this issue as well, you can use canvasRef.current.toImage().encodeToBase64() instead of it. it's being used incorrect ImageFormat type caused it I guess.

Thanks works.
