### ISSUE TITLE
iOS/Expo support?

### ISSUE THREAD

**Issue by za01br** [wobsoriano/rn-perfect-sketch-canvas#15]
Hey!
First of all, thanks for the hard work on this, looks exactly what I need for a small project. =P
Is this correct that this library only works for Android and Web? (https://reactnative.directory/?search=sketch)
I'm using Expo to create a cross-platform app and wanted to use this for both, iOS and Android if possible.
Thank you!

**Comment by wobsoriano** [comment]
Latest version of rn skia supports expo so this works with expo too

**Comment by za01br** [comment]
@wobsoriano Thanks, I will give it a try and get back to you!
