### ISSUE TITLE
Failing in production build

### ISSUE THREAD

**Issue by abdullahIsa** [wobsoriano/rn-perfect-sketch-canvas#3]
In development without creating a build everything works well but when i created a build for production and installed on another phone for testing it keeps throwing errors.

**using react-native: "0.68.1" but with fabric or new architecture off**

![photo_2022-05-03_01-08-41](https://user-images.githubusercontent.com/49385380/166293142-9ec7e179-94fb-420e-afbb-09fe83c40b05.jpg)

**Comment by wobsoriano** [comment]
Can you try a build with just rn skia installed and a simple canvas?

**Comment by wobsoriano** [comment]
Do you still get this in [v0.1.130-alpha](https://github.com/Shopify/react-native-skia/releases/tag/v0.1.130-alpha)? Please feel free to reopen if yes. Thanks!
