### ISSUE TITLE
Is it possible to have a background image and also have that saved?

### ISSUE THREAD

**Issue by joshua-revolutions** [wobsoriano/rn-perfect-sketch-canvas#6]
react-native-sketch-canvas had the ability to use a background image. This image would also be saved when calling the save function together with the path. Is the feature available?

**Comment by TwanLuttik** [comment]
If you're looking for a temporary work around, what i do is overlaying this component on top of an image and using `backgroundColor: "transparent"` and would snap a image by using `react-native-view-shot`

![CleanShot 2022-07-12 at 10 21 37](https://user-images.githubusercontent.com/19343894/178554752-1320c778-a7c0-4a8a-b186-e8528442620b.png)
as you see the tesla car is an image overlay with the sketch on top

**Comment by soorajpandey** [comment]
hello @TwanLuttik, I tried your solution but it didn't work, could you please explain a little or could you give a code snippet?
thank you

**Comment by TwanLuttik** [comment]
To give you a little run down, you need to put everything into the `<ViewShot/>` component and you basically have the `<SketchCanvas />` hovering over the image with position absolute and a transparent background. and the viewshot will capture what you see in that view.

```
const test = () => {
  return <View>
    <ViewShot
      ref={ViewShotRef}
      options={{
        format: "png",
        quality: 1,
      }}
    >
      <FastImage
        source={Image.resolveAssetSource(teslaImageAsset)}
        style={{
          height: (9 / 16) * imageWidth,
          width: imageWidth
        }}
      />
      <SketchCanvas
        ref={canvasRef}
        containerStyle={{
          position: "absolute",
          flex: 1,
          backgroundColor: "transparent",
          height: (9 / 16) * imageWidth,
          width: imageWidth,
        }}
      />
    </ViewShot>
  </View>
}
```

Technically you don't need viewshot, there are tricks to merge 2 images images together but this is a easy way to do as i found out.

**Comment by soorajpandey** [comment]
thank you @TwanLuttik, I am able to solve it, this is my code

```
<ImageZoom cropWidth={Dimensions.get('window').width}
                        cropHeight={Dimensions.get('window').height / 1.2}
                        imageWidth={Dimensions.get('window').width}
                        imageHeight={Dimensions.get('window').width / 1.6}
                        panToMove={false}>
                        <View style={Styles.imageContainer}>
                          <View style={Styles.backgroundContainer}>
                            <FastImage
                              source={{
                                uri: `${showImage.path}`,
                                priority: FastImage.priority.high,
                                cache: FastImage.cacheControl.immutable,
                              }}
                              resizeMode={FastImage.resizeMode.contain}
                              style={Styles.backdrop}
                            />
                          </View>
                          <View style={Styles.overlay}>
                            <View
                              style={{
                                width: Dimensions.get('window').width,
                                height: Dimensions.get('window').width / 1.6,
                                backgroundColor: 'transparent',
                                borderRadius: 10,
                              }}
                            >
                              <SketchCanvas
                                strokeColor={snap.strokeColor}
                                strokeWidth={snap.strokeWidth}
                                ref={canvasRef}
                                containerStyle={styles.container}
                              />
                            </View>
                          </View>
                        </View>
                      </ImageZoom>
```

![IMG_0986](https://user-images.githubusercontent.com/42384377/178964633-6907de39-2aca-4e42-8ac5-e72ac1d8c102.jpg)

I am getting a few issues while using [ImageZoom Library](https://github.com/ascoders/react-native-image-zoom) when wrapping everything around it I am not able to create any line, just a temporary dot is rendering. If you could give me any hint on how could I achieve it, that would be very helpful.

thank you.

**Comment by TwanLuttik** [comment]
You can use `canvasRef.current?.toPoints()` to save the draw line data and put it back with `canvasRef.current?.addPoints(data)` but there is i downside with it and it doesn't put it back with styling, i have a issue open for that and going to create a pr for it to solve that issue. (If you want a [patch-patch](https://www.npmjs.com/package/patch-package) package in the meantime i can give it to you)

**Comment by soorajpandey** [comment]
thank you, I am able to zoom and edit just by using a simple gesture handler (onGestureEvent) and Animated View.

**Comment by wobsoriano** [comment]
please update to v3 and use `topChildren`/`bottomChildren` props:

```js
export default function App() {
  return (
    <SafeAreaView>
      <SketchCanvas
        bottomChildren={
          <Path
            path="M 128 0 L 168 80 L 256 93 L 192 155 L 207 244 L 128 202 L 49 244 L 64 155 L 0 93 L 88 80 L 128 0 Z"
            color="lightblue"
          />
        }
      />
    </SafeAreaView>
  );
}
```
<img width="406" alt="Screen Shot 2022-08-03 at 3 06 12 PM" src="https://user-images.githubusercontent.com/13049130/182720815-134ba4e2-9bda-4aaf-8131-f98d13bf26f2.png">
