### ISSUE TITLE
addPoints() is not setting with the color that have been provided as prop

### ISSUE THREAD

**Issue by TwanLuttik** [wobsoriano/rn-perfect-sketch-canvas#8]
When i do 
```canvasRef.current?.addPoints()```

Its not setting with the prop styling i have provided.

**Comment by TwanLuttik** [comment]
i have created a pr as suggestions to make it work if you like this way

- https://github.com/wobsoriano/rn-perfect-sketch-canvas/pull/9

**Comment by wobsoriano** [comment]
Added in v0.1.6
